//
//  MyStyleKit.h
//  ProjectName
//
//  Created by AuthorName on 5/27/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface StyleKit : NSObject

// Colors
+ (UIColor*)color;

// Drawing Methods
+ (void)drawTimeBlockWithFrame: (CGRect)frame;

@end
